NAME = "Landing Page"
SLUG = "landing-page"
DESCRIPTION = "Organize landing pages within your dashboard."
VERSION = "0.1-dev"
DEPENDENCIES = []
AUTHOR = "Thaddeus Toledo"
URL_PREFIX = ""
STATIC_FOLDER = "static"
TEMPLATE_FOLDER = "templates"
