"""auto migration for landing_page

Revision ID: 020f635e184e
Revises: eda86f7b7d80
Create Date: 2026-06-09 13:00:59.310037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020f635e184e'
down_revision = 'eda86f7b7d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint('uq_visitor_visitor_id', ['visitor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_constraint('uq_visitor_visitor_id', type_='unique')
        batch_op.drop_column('visitor_id')

    # ### end Alembic commands ###
