"""image on team member

Revision ID: 1702e849015e
Revises: 80d5292160ac
Create Date: 2026-08-09 14:46:05.099158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1702e849015e'
down_revision = '80d5292160ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
