"""image on team member

Revision ID: 1702e849015e
Revises: 80d5292160ac
Create Date: 2026-08-09 14:46:05.099158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1702e849015e'
down_revision = '80d5292160ac'
branch_labels = None
depends_on = None

def has_column(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        if not has_column('team_member', 'image'):
            batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        if has_column('team_member', 'image'):
            batch_op.drop_column('image')

    # ### end Alembic commands ###
