"""removed session id chat messages will use client uuid as identifier

Revision ID: 2c827b79fd99
Revises: 85e4b04b34de
Create Date: 2026-07-18 19:05:27.052542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c827b79fd99'
down_revision = '85e4b04b34de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_support_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('session_id'))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_support_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.create_index(batch_op.f('session_id'), ['session_id'], unique=True)

    # ### end Alembic commands ###
