"""updated phone number data type

Revision ID: 30b714cc7d99
Revises: b54a9d03cbeb
Create Date: 2026-08-09 16:18:43.757280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30b714cc7d99'
down_revision = 'b54a9d03cbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
