"""auto migration for landing_page

Revision ID: 58a7a4a0b197
Revises: baaa9b24c918
Create Date: 2026-05-28 14:44:11.365874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a7a4a0b197'
down_revision = 'baaa9b24c918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
