"""empty message

Revision ID: 7de503ec3239
Revises: 58a7a4a0b197
Create Date: 2026-05-28 15:48:58.854416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de503ec3239'
down_revision = '58a7a4a0b197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
