"""added the foreign keys for live chat messages

Revision ID: 80d5292160ac
Revises: 2c827b79fd99
Create Date: 2026-07-18 19:18:33.400412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d5292160ac'
down_revision = '2c827b79fd99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
