"""added the foreign keys for live chat messages

Revision ID: 80d5292160ac
Revises: 2c827b79fd99
Create Date: 2026-07-18 19:18:33.400412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d5292160ac'
down_revision = '2c827b79fd99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('moderator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['moderator_id'], ['id'])
        batch_op.create_foreign_key(None, 'chat_support_client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('moderator_id')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
