"""added session id on chat support client model

Revision ID: 85e4b04b34de
Revises: 7e6fbf1ec4d4
Create Date: 2026-07-18 12:35:51.888874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e4b04b34de'
down_revision = '7e6fbf1ec4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_support_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_support_client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
