"""auto migration for landing_page

Revision ID: baaa9b24c918
Revises: 4feb6a0ecfde
Create Date: 2026-05-28 14:44:10.402318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baaa9b24c918'
down_revision = '4feb6a0ecfde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
