"""added a visitor and visit model to track landing page visits

Revision ID: eda86f7b7d80
Revises: 7de503ec3239
Create Date: 2026-06-09 12:59:40.662785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda86f7b7d80'
down_revision = '7de503ec3239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
